
### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

#\#Hotel API

GET {{url}}/hotels

###

GET {{url}}/hotels/2

###

POST {{url}}/hotels
Content-Type: application/json

{
  "hotelName": "Holiday Inn",
  "hotelAddress": "Stuttgart",
  "hotelType": "STANDARD"
}

###

PUT {{url}}/hotels/3
Content-Type: application/json

{
  "hotelName": "Ritz Carlton",
  "hotelAddress": "London City",
  "hotelType": "LUXURY"
}

###

DELETE {{url}}/hotels/5

###

// Room API

GET {{url}}/rooms

###

GET {{url}}/rooms/1

###

POST {{url}}/rooms/hotel/3
Content-Type: application/json

{
  "roomNumber": 11,
  "roomPrice": 1150,
  "roomType": "SINGLE"
}
