### GET request to example server
### A simple get request to the test endpoint. No need for login
GET {{url}}/recipes

### get a recippe by id
GET {{url}}/recipes/8

### Create a new user
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "1234"
}

### Login with user
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}
### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}


### Create a new recipe
POST {{url}}/recipes
Authorization: Bearer {{jwt_token}}

{
    "title": "emil",
    "ingredientsAndGrams": "100 g chokolade",
    "description": "smelt chokolade",
    "difficulty": "EASY"

}

### Add regular role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "regular"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}





###